# # Laptop monitor - always exists
monitor = eDP-1, 2560x1440@60, 0x0, 1.6
# monitor = eDP-1, preferred, 0x0, 1

# # External monitor - with fallback so it doesn't break when unplugged
# monitor=HDMI-A-1,1920x1080@89.93,1920x0,1.0
# monitor = , preferred, auto, 1  # fallback for any other monitor
